export const GithubPublicUserDataType = {
  login: "BishalN",
  id: 50773789,
  node_id: "MDQ6VXNlcjUwNzczNzg5",
  avatar_url: "https://avatars.githubusercontent.com/u/50773789?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/BishalN",
  html_url: "https://github.com/BishalN",
  followers_url: "https://api.github.com/users/BishalN/followers",
  following_url: "https://api.github.com/users/BishalN/following{/other_user}",
  gists_url: "https://api.github.com/users/BishalN/gists{/gist_id}",
  starred_url: "https://api.github.com/users/BishalN/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/BishalN/subscriptions",
  organizations_url: "https://api.github.com/users/BishalN/orgs",
  repos_url: "https://api.github.com/users/BishalN/repos",
  events_url: "https://api.github.com/users/BishalN/events{/privacy}",
  received_events_url: "https://api.github.com/users/BishalN/received_events",
  type: "User",
  site_admin: false,
  name: "Bishal Neupane",
  company: null,
  blog: "https://bishaln.github.io/",
  location: null,
  email: null,
  hireable: true,
  bio: "Full Stack Developer",
  twitter_username: null,
  public_repos: 67,
  public_gists: 0,
  followers: 3,
  following: 26,
  created_at: "2019-05-18T14:15:53Z",
  updated_at: "2021-10-25T16:55:13Z",
};

export type githubType = typeof GithubPublicUserDataType;
