import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import * as Yup from "yup";

import { Button, OauthButton } from "../components/Button";
import { useRouter } from "next/dist/client/router";
import { Formik, Form, Field } from "formik";
import { ErrorMsg } from ".";
import useRegister from "../hooks/mutation/useRegister";

const Home: NextPage = () => {
  const { isLoading, mutateAsync } = useRegister();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        {/* nav section */}
        <section>
          <h1 className="text-5xl m-5">MyNotes</h1>
        </section>

        {/* by default the index page would be the login page */}
        <main>
          <section>
            <div
              className="bg-gray-200 my-10
             rounded-md  flex flex-col mx-3 p-6
              space-y-4 justify-center items-center md:mx-28 lg:mx-56 xl:mx-96"
            >
              <div className="self-start">
                <h3 className="text-5xl">Welcome</h3>
                <h3 className="ml-2">
                  By registering you accept our{" "}
                  <span className="text-blue-700 cursor-pointer">
                    Privacy Policy
                  </span>{" "}
                  and
                  <span className="text-blue-700 cursor-pointer">
                    {" "}
                    Terms of Service
                  </span>
                </h3>
              </div>

              <Formik
                initialValues={{ email: "", password: "", name: "" }}
                validationSchema={Yup.object({
                  email: Yup.string()
                    .email("Invalid email address")
                    .required("Required"),
                  password: Yup.string()
                    .min(6, "Must be atleast 6 characters long")
                    .required("Required"),
                  name: Yup.string()
                    .min(3, "Must be atleast 3 characters long")
                    .required("Required"),
                })}
                onSubmit={async (values, { setSubmitting }) => {
                  console.log("submitted");
                  await mutateAsync(values, {
                    onSettled: (data) => {
                      console.log(data);
                      setSubmitting(false);
                    },
                  });
                }}
              >
                <Form className="flex flex-col w-full space-y-2 text-center">
                  <label htmlFor="name" className="self-start">
                    Full Name
                  </label>
                  <Field name="name" type="text" />
                  <ErrorMsg name="name" />

                  <label htmlFor="email" className="self-start">
                    Email Address
                  </label>
                  <Field name="email" type="text" />
                  <ErrorMsg name="email" />

                  <label className="self-start" htmlFor="password">
                    Password
                  </label>
                  <Field name="password" type="password" />
                  <ErrorMsg name="password" />

                  <Button loading={isLoading} type="submit">
                    Register
                  </Button>
                  <span>
                    Don't have an account?{" "}
                    <span className="text-blue-500">
                      <Link href="/">Login</Link>
                    </span>
                  </span>
                  <div className="border-b-2 w-64 self-center border-black"></div>
                </Form>
              </Formik>

              <OauthButton provider="facebook">
                Continue with facebook
              </OauthButton>
              <OauthButton provider="google">Continue with google</OauthButton>
              <OauthButton provider="github">Continue with github</OauthButton>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
};

export default Home;
