name: backend:previewtestdeploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    branches:
      - staging
    paths:
      - ".github/workflows/backend-preview-test-deploy.yaml"
      - "backend/**/**"
  pull_request:
    branches:
      - staging
    paths:
      - "backend/**/**"
jobs:
  previewtestdeploy:
    name: previewtestdeploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mynotes_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install yarn globally
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run database migration
        run: yarn tmg
      - name: Run tests
        run: yarn test
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cat key.txt
