name: backend:previewtestdeploy

on:
  push:
    branches:
      - staging
    paths:
      - ".github/workflows/backend-preview-test-deploy.yaml"
      - "backend/**/**"
  pull_request:
    branches:
      - staging
    paths:
      - "backend/**/**"
jobs:
  previewtestdeploy:
    name: previewtestdeploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    # services:
    #   db:
    #     image: postgres:11
    #     ports: ["5432:5432"]
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: mynotes_test
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      # - name: Install yarn globally
      #   run: npm i -g yarn
      # - name: Install dependencies
      #   run: yarn
      # - name: Run database migration
      #   run: yarn tmg
      # - name: Run tests
      #   run: yarn test
      - name: Build docker image
        run: docker build -t bsal/mynotes_staging .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image to docker hub
        run: docker push bsal/mynotes_staging
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}
      - name: Deploy the docker image to azure containers
        uses: Azure/aci-deploy@v1
        with:
          resource-group: mynotes
          dns-name-label: mynotestaging
          image: bsal/mynotes_staging
          name: mynotestaging
          location: "Central India"
          memory: 0.5
          restart-policy: OnFailure
          ports:
            - 80
            - 4000
