name: backend:previewtestdeploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    branches:
      - staging
    paths:
      - ".github/workflows/backend-preview-test-deploy.yaml"
      - "backend/**/**"
  pull_request:
    branches:
      - staging
    paths:
      - "backend/**/**"
jobs:
  previewtestdeploy:
    name: previewtestdeploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mynotes_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Print the current working directory
        run: pwd
      - name: Install yarn globally
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run database migration
        run: yarn tmg
      - name: Run tests
        run: yarn test
      - name: Workaround issue
        run: git config user.email "neupanebishal07@gmail.com" && git config user.name "bishalneupane" && git add -A && git commit -m "Updated code"
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bishalmynotespreview"
          heroku_email: "bishalisontheline@gmail.com"
          appdir: "backend"
          branch: "staging"
          usedocker: true
