name: web:e2e_tests
on:
  push:
    branches:
      - staging
    paths:
      - ".github/workflows/web-e2e_tests.yaml"
      - "web/src/**"
  pull_request:
    branches:
      - staging
    paths:
      - "web/src/**"
jobs:
  end-to-end-tests:
    name: end-to-end-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mynotes_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install yarn globally
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run database migration
        run: yarn tmg
      - name: Build the app server
        run: yarn build
      - name: Start the app server
        run: yarn start
      - name: Run e2e tests
        run: cd ../web && yarn test:e2e:ci
