name: web:e2e_tests
on:
  push:
    branches:
      - staging
    paths:
      - ".github/workflows/web-e2e_tests.yaml"
      - "web/src/**"
  pull_request:
    branches:
      - staging
    paths:
      - "web/src/**"
jobs:
  end-to-end-tests:
    name: end-to-end-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install yarn globally
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run e2e tests
        run: yarn test:e2e:ci
