name: web:unit-tests

on:
  push:
    branches:
      - staging
    paths:
      - "web/**"
      - ".github/workflows/web-test.yaml"
  pull_request:
    branches:
      - staging
    paths:
      - "web/**"

jobs:
  test:
    name: unit-tests-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: cd web && yarn install
      - run: cd web && yarn test:ci
        id: test
