name: web:prod-e2e-and-unit_tests
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/web-prod-e2e-unit_test.yaml"
      - "web/**"
  pull_request:
    branches:
      - master
    paths:
      - "web/**"
jobs:
  prod-e2e-and-unit_tests:
    name: prod-e2e-and-unit_tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install yarn globally
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test:ci
      - name: Run e2e tests
        run: yarn test:e2e:ci
